version: "3.9"

services:

  de_mysql:
    image: "mariadb"
    container_name: de_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - kyuubi_network

  minio:
    hostname: minio
    image: "minio/minio"
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - ./minio/data:/data
    env_file:
      - .env
    networks:
      - kyuubi_network

  apache_kyuubi:
    image: apache/kyuubi:master-snapshot
    container_name: apache_kyuubi
    ports:
      - "10009:10009"
      - "4040:4040"
    networks:
      - kyuubi_network

  hive-metastore:
    container_name: hive-metastore
    hostname: hive-metastore
    image: "bitsondatadev/hive-metastore"
    ports:
      - "9083:9083"
    volumes:
      - ./hive-metastore/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: de_mysql
    networks:
      - kyuubi_network
    depends_on:
      - de_mysql
      - minio

  trino:
    container_name: trino
    image: "trinodb/trino"
    hostname: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino:/etc/trino
    networks:
      - kyuubi_network

networks:
  kyuubi_network:
    driver: bridge
    name: kyuubi_network
