version: "3.9"

services:

  de_mysql:
    image: "mariadb"
    container_name: de_mysql
    command: --max_connections=500
    healthcheck:
      test: CMD-SHELL mysqladmin ping -h 127.0.0.1 -u root -p"$MYSQL_ROOT_PASSWORD" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - data_network
      
  de_psql:
    image: postgres:15
    container_name: de_psql
    healthcheck:
      test: CMD-SHELL pg_isready -U "$POSTGRES_USER"
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - data_network

  minio:
    hostname: minio
    image: "minio/minio"
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data
    env_file:
      - .env
    networks:
      - data_network

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    hostname: hive-metastore    
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9083"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9083:9083"
    env_file:
      - .env
    volumes:
      - ./docker/hive-metastore/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: ${MYSQL_HOST}
    networks:
      - data_network
    depends_on:
      de_mysql:
        condition: service_healthy
      minio:
        condition: service_healthy

  trino:
    image: "trinodb/trino"
    container_name: trino
    hostname: trino
    depends_on:
      hive-metastore:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./docker/trino:/etc/trino
    networks:
      - data_network

  spark-master:
    build:
      context: ./docker/spark
      dockerfile: ./Dockerfile
    container_name: "spark-master"
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
    ports:
      - "7077:7077"
    volumes:
      - ./docker/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - data_network

  spark-worker-1:
    image: docker.io/bitnami/spark:3.3
    container_name: "spark-worker-1"
    env_file:
      - .env
    volumes:
      - ./docker/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    depends_on:
      - spark-master
    networks:
      - data_network

  spark-worker-2:
    image: docker.io/bitnami/spark:3.3
    container_name: "spark-worker-2"
    env_file:
      - .env
    volumes:
      - ./docker/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    depends_on:
      - spark-master
    networks:
      - data_network

  spark-thrift-server:
    build:
      context: ./docker/spark
      dockerfile: ./Dockerfile
    container_name: "spark-thrift-server"
    depends_on:
      - spark-master
      - hive-metastore
    ports:
      - "4040:4040"
      - "10000:10000"
    command: >
      sh -c "
        until nc -z hive-metastore 9083; do
          echo 'Waiting for hive-metastore:9083...'
          sleep 2
        done
        echo 'Hive Metastore is up - starting Spark Thrift Server'
        ./sbin/start-thriftserver.sh --driver-java-options '-Dhive.metastore.uris=thrift://hive-metastore:9083' --master spark://spark-master:7077
      "
    volumes:
      - ./docker/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - data_network

  metabase:
    image: metabase/metabase:latest
    container_name: "metabase"
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - data_network

volumes:
  psql_data:
  mysql_data:
  minio_data:

networks:
  data_network:
    driver: bridge
    name: data_network
