version: "3.9"

services:

  de_mysql:
    image: "mariadb"
    container_name: de_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - kyuubi_network

  minio:
    hostname: minio
    image: "minio/minio"
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - ./minio/data:/data
    env_file:
      - .env
    networks:
      - kyuubi_network

  hive-metastore:
    build:
      context: ./hive-metastore
      dockerfile: ./Dockerfile
    container_name: "hive-metastore"    
    image: hive-metastore:latest
    ports:
      - "9083:9083"
    depends_on:
      - de_mysql
    networks:
      - kyuubi_network      

  trino:
    container_name: trino
    image: "trinodb/trino"
    hostname: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino:/etc/trino
    networks:
      - kyuubi_network

  spark-master:
    build:
      context: ./spark
      dockerfile: ./Dockerfile
    container_name: "spark-master"
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
    ports:
      - "7077:7077"
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - kyuubi_network

  spark-worker-1:
    image: docker.io/bitnami/spark:3.3
    container_name: "spark-worker-1"
    env_file:
      - .env
    depends_on:
      - spark-master
    networks:
      - kyuubi_network

  spark-worker-2:
    image: docker.io/bitnami/spark:3.3
    container_name: "spark-worker-2"
    env_file:
      - .env
    depends_on:
      - spark-master
    networks:
      - kyuubi_network

  spark-thrift-server:
    build:
      context: ./spark
      dockerfile: ./Dockerfile
    container_name: "spark-thrift-server"
    depends_on:
      - spark-master
      - hive-metastore
    ports:
      - "4040:4040"
      - "10000:10000"
    command: sh -c "
        sleep 10 && ./sbin/start-thriftserver.sh --files /opt/bitnami/spark/conf/hive-site.xml --master spark://spark-master:7077"
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
    networks:
      - kyuubi_network
        
networks:
  kyuubi_network:
    driver: bridge
    name: kyuubi_network
