version: 2

sources:
  - name: mysql_src
    description: "Raw MySQL tables via Trino"
    tables:
      - name: olist_order_items_dataset
      - name: olist_order_payments_dataset
      - name: olist_orders_dataset
      - name: olist_products_dataset
      - name: product_category_name_translation