version: 2

models:
  - name: dim_products
    description: Product dimension table with English category names
    columns:
      - name: product_id
        data_type: string
        description: Product unique identifier
        tests:
          - unique
          - not_null
      - name: product_category_name_english
        data_type: string
        description: Product category name in English
        tests:
          - not_null
          - valid_category_counts

  - name: fact_sales
    description: Sales fact table with order details and payments
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: source('bronze', 'olist_order_items')
      - payment_matches_items
    columns:
      - name: order_id
        data_type: string
        description: Order unique identifier
        tests:
          - not_null
      - name: customer_id
        data_type: string
        description: Customer unique identifier
        tests:
          - not_null
      - name: order_purchase_timestamp
        data_type: timestamp
        description: Purchase timestamp
        tests:
          - not_null
          - dbt_utils.is_timestamp
          - order_dates_are_valid
      - name: product_id
        data_type: string
        description: Product identifier
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
      - name: payment_value
        data_type: float
        description: Payment amount
        tests:
          - not_null
          - dbt_utils.positive_value
          - reasonable_payment_value
      - name: order_status
        data_type: string
        description: Current order status
        tests:
          - not_null
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'unavailable', 'invoiced', 'processing', 'created', 'approved']

sources:
  - name: bronze
    description: "Iceberg tables from bronze layer"
    tables:
      - name: olist_products
        external:
          location: 's3a://warehouse/bronze/olist_products'
          using: iceberg
      - name: olist_orders
        external:
          location: 's3a://warehouse/bronze/olist_orders'
          using: iceberg
      - name: olist_order_items
        external:
          location: 's3a://warehouse/bronze/olist_order_items'
          using: iceberg
      - name: olist_order_payments
        external:
          location: 's3a://warehouse/bronze/olist_order_payments'
          using: iceberg
      - name: product_category_name_translation
        external:
          location: 's3a://warehouse/bronze/product_category_name_translation'
          using: iceberg